baseURL = "https://bodo-apps.github.io/bodo"
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'bodo (ボード)'
theme = 'hugo-tranquilpeak-theme'
publishDir = "../docs"
canonifyurls = true # 追加(相対URLを絶対URLに変換できるようにする)

# HTMLタグを使用
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 記事のカテゴリーなどを紐付け
[taxonomies]
  tag = "tags"

[author]
  name = "bodo-apps"
  bio = "小さなボードゲームたちが集まるところ"
  job = "GitHubコントリビューター"
  location = "Japan"
  picture = "images/team.png" # themes/static/

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  dateFormat = "2006-01-02"
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
  coverImage = "images/cover.jpg"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
  relativeURLs = true

# weight == sort

# content/pages につながる
[[menu.main]]
  weight = 1
  identifier = "docs"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/docs/hello/"
[[menu.main]]
  weight = 2
  identifier = "tags" # id == tags の場合は特別な処理がされる
  name = "タグ検索"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 3
  identifier = "bodo"
  name = "bodo"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-pen-nib\" aria-hidden=\"true\"></i>"
  url = "/bodo/root/"
[[menu.main]]
  weight = 4
  identifier = "users"
  name = "users"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-pen-nib\" aria-hidden=\"true\"></i>"
  url = "/users/"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/bodo-apps/bodo"
